In [2]:
import numpy as np
import pandas as pd
import matplotlib as mlt
# اسم ملف الإكسيل بتاعك
file_path = 'Manufacturing_Line_Productivity.xlsx'

df_productivity = pd.read_excel(file_path,sheet_name='Line productivity' ,parse_dates=['Date', 'Start Time', 'End Time'])
df_products     = pd.read_excel(file_path, sheet_name='Products')
df_factors      = pd.read_excel(file_path, sheet_name='Downtime factors')
df_downtime     = pd.read_excel(file_path, sheet_name='Line downtime', skiprows=1)
print("تم رفع جميع الشيتات بنجاح!")

تم رفع جميع الشيتات بنجاح!

C:\Users\Midoz\AppData\Local\Temp\ipykernel_10080\1377439882.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_productivity = pd.read_excel(file_path,sheet_name='Line productivity' ,parse_dates=['Date', 'Start Time', 'End Time'])
C:\Users\Midoz\AppData\Local\Temp\ipykernel_10080\1377439882.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_productivity = pd.read_excel(file_path,sheet_name='Line productivity' ,parse_dates=['Date', 'Start Time', 'End Time'])

In [3]:
df_productivity = pd.read_excel(file_path,sheet_name='Line productivity' ,parse_dates=['Date', 'Start Time', 'End Time'])
df_productivity['Date'] = pd.to_datetime(df_productivity['Date'], dayfirst=True, errors='coerce')
df_productivity.columns = df_productivity.columns.str.strip()
df_productivity['Gross_Minutes'] = (df_productivity['End Time'] - df_productivity['Start Time']).dt.total_seconds() / 60
df_productivity['Start Time'] = df_productivity['Start Time'].dt.time
df_productivity['End Time'] = df_productivity['End Time'].dt.time
df_productivity.head()

C:\Users\Midoz\AppData\Local\Temp\ipykernel_10080\3255957776.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_productivity = pd.read_excel(file_path,sheet_name='Line productivity' ,parse_dates=['Date', 'Start Time', 'End Time'])
C:\Users\Midoz\AppData\Local\Temp\ipykernel_10080\3255957776.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_productivity = pd.read_excel(file_path,sheet_name='Line productivity' ,parse_dates=['Date', 'Start Time', 'End Time'])

        Date Product   Batch Operator Start Time  End Time  Gross_Minutes
0 2024-08-29  OR-600  422111      Mac   11:50:00  14:05:00          135.0
1 2024-08-29  LE-600  422112      Mac   14:05:00  15:45:00          100.0
2 2024-08-29  LE-600  422113      Mac   15:45:00  17:35:00          110.0
3 2024-08-29  LE-600  422114      Mac   17:35:00  19:15:00          100.0
4 2024-08-29  LE-600  422115  Charlie   19:15:00  20:39:00           84.0

In [4]:
df_productivity.info()
print('number of duplicates :' + str(df_productivity.duplicated().sum()))
### cheking coulmns name
##df_productivity.columns
df_productivity.rename(columns={'Product': 'Product_Id'}, inplace=True)
df_productivity.rename(columns={'Batch': 'Batch_Id'}, inplace=True)
df_productivity.rename(columns={'Operator': 'Operator_name'}, inplace=True)
df_productivity.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           38 non-null     datetime64[ns]
 1   Product        38 non-null     object
 2   Batch          38 non-null     int64
 3   Operator       38 non-null     object
 4   Start Time     38 non-null     object
 5   End Time       38 non-null     object
 6   Gross_Minutes  38 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 2.2+ KB
number of duplicates :0

Date             0
Product_Id       0
Batch_Id         0
Operator_name    0
Start Time       0
End Time         0
Gross_Minutes    0
dtype: int64

In [5]:

df_products.info()
# استبدال "2 L" بـ "2000 ml" مباشرة في العمود
## هنا عملنا replace علي طول 
df_products['Size'] = df_products['Size'].replace('2 L', '2000 ml')
##df_products
### cheking coulmns name
##df_products.columns
df_products.rename(columns={'Product': 'Product_Id'}, inplace=True)
df_products.isnull().sum()
df_products.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product         6 non-null      object
 1   Flavor          6 non-null      object
 2   Size            6 non-null      object
 3   Min batch time  6 non-null      int64
dtypes: int64(1), object(3)
memory usage: 324.0+ bytes

  Product_Id      Flavor    Size  Min batch time
0     OR-600      Orange  600 ml              60
1     LE-600  Lemon lime  600 ml              60
2     CO-600        Cola  600 ml              60
3     DC-600   Diet Cola  600 ml              60
4     RB-600  Root Berry  600 ml              60

In [6]:
df_factors.info()
print('number of duplicates :' + str(df_factors.duplicated().sum()))
### cheking coulmns name
##df_factors.columns
df_factors.rename(columns={'Factor': 'Factor_Id'}, inplace=True)
df_factors.isnull().sum()
df_factors.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Factor          12 non-null     int64
 1   Description     12 non-null     object
 2   Operator Error  12 non-null     object
dtypes: int64(1), object(2)
memory usage: 420.0+ bytes
number of duplicates :0

   Factor_Id         Description Operator Error
0          1      Emergency stop             No
1          2        Batch change            Yes
2          3      Labeling error             No
3          4  Inventory shortage             No
4          5       Product spill            Yes

In [33]:
df_downtime.head(2) 
## دا شكل الفايل القديم

    Batch   1     2   3   4   5   6     7     8   9  10  11  12
0  422111 NaN  60.0 NaN NaN NaN NaN  15.0   NaN NaN NaN NaN NaN
1  422112 NaN  20.0 NaN NaN NaN NaN   NaN  20.0 NaN NaN NaN NaN

In [9]:
# 1. قراءة الشيت (مع تخطي السطر الأول)
file_path = 'Manufacturing_Line_Productivity.xlsx'
df_downtime = pd.read_excel(file_path, sheet_name='Line downtime', skiprows=1)

# 2. تحويل الأعمدة (1-12) لصفوف
df_melted = df_downtime.melt(
    id_vars=['Batch'], 
    var_name='Downtime factor', 
    value_name='Minutes'
)
# 3. حذف الصفوف اللي مفيهاش دقائق (الفاضية)
# دي خطوة مهمة عشان الـ ID ميروحش لصفوف فاضية ملهاش لازمة
df_downtime_Final = df_melted.dropna(subset=['Minutes']).copy()

# 4. إعادة ترتيب البيانات حسب الباتش (اختياري لكن يفضل للتنظيم)
df_downtime_Final = df_downtime_Final.sort_values(by='Batch').reset_index(drop=True)

# 5. إنشاء الـ downtime_id كعداد مسلسل للصفوف (يبدأ من 1)
df_downtime_Final['downtime_id'] = range(1, len(df_downtime_Final) + 1)

# 6. إعادة ترتيب الأعمدة لتطابق الصورة اللي بعتها
df_downtime_Final = df_downtime_Final[['Batch', 'Downtime factor', 'Minutes', 'downtime_id']]
##df_downtime_Final

In [10]:
df_downtime_Final.info()
print('number of duplicates :' + str(df_downtime_Final.duplicated().sum()))
df_downtime_Final.isnull().sum()
### الوصف هنا للبيانات دي ليس له جدوي لانها ليست ارقام كميه 
##df_downtime_Final.describe()
df_downtime_Final.rename(columns={'Batch': 'Batch_Id'}, inplace=True)
df_downtime_Final.rename(columns={'Downtime factor': 'Factor_Id'}, inplace=True)
df_downtime_Final.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Batch            61 non-null     int64
 1   Downtime factor  61 non-null     object
 2   Minutes          61 non-null     float64
 3   downtime_id      61 non-null     int64
dtypes: float64(1), int64(2), object(1)
memory usage: 2.0+ KB
number of duplicates :0

   Batch_Id Factor_Id  Minutes  downtime_id
0    422111         2     60.0            1
1    422111         7     15.0            2
2    422112         2     20.0            3
3    422112         8     20.0            4
4    422113         2     50.0            5